# Declara que vamos usar a rede externa que já foi criada manualmente
networks:
  radares-net:
    external: true

services:
  # Define o serviço para a aplicação de monitoramento
  microservico-monitoramento:
    container_name: microservico-monitoramento
    # Constrói a imagem a partir do Dockerfile que está nesta mesma pasta
    build:
      context: .
    ports:
      # Expõe a porta da aplicação (ex: 8082) para a sua máquina local
      - "8089:8089"
    environment:
      # Ativa o perfil de produção para usar o application-prod1.properties
      - SPRING_PROFILES_ACTIVE=prod
      # As variáveis para o Telegram serão lidas de um arquivo .env nesta pasta
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Nota: A URL aponta para 'postgres-db' que é o nome do container na Stack EFK
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/monitoramento_db
      # Conecta no RabbitMQ da Stack EFK (nome do serviço: rabbitmq)
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EVOLUTION_API_URL=http://evolution-api:8080
      - EVOLUTION_API_TOKEN=${EVOLUTION_API_TOKEN}
      - EVOLUTION_API_INSTANCE=RadarBot
    networks:
      # Conecta este contêiner à nossa rede compartilhada
      - radares-net
    restart: unless-stopped
    depends_on:
      - evolution-api
  # Novo serviço: Evolution API
  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:v2.2.2
    restart: always
    ports:
      - "8090:8080" # Acesso externo via http://localhost:8090
    # === ADICIONE ISSO AQUI PARA CORRIGIR O TIMEOUT ===
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_URL=http://localhost:8090
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_TOKEN}
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/monitoramento_db?schema=evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_v2
      # === REDIS (Correção do erro "disconnected") ===
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      # Opcional: Desativar RabbitMQ se não estiver usando para a Evolution
      - RABBITMQ_ENABLED=false
      # Aumenta o timeout do WebSocket
      - WEBSOCKET_PING_INTERVAL=20000
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - radares-net
    depends_on:
      - redis

  evolution-manager:
    container_name: evolution-manager
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "8091:80" # Porta para acessar o painel (8091)
    environment:
      # URL da sua API (como seu navegador vê a API)
      - VITE_API_URL=http://localhost:8090
    networks:
      - radares-net
    depends_on:
      - evolution-api
    # === CORREÇÃO TEMPORÁRIA DO BUG DO NGINX ===
    entrypoint: /bin/sh
    command: >
      -c "sed -i 's/ must-revalidate//g' /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"

  redis:
    image: redis:latest
    container_name: redis_evolution
    command: ["redis-server", "--appendonly", "yes"]
    #volumes:
    #  - redis_data:/data
    networks:
      - radares-net
    restart: always

volumes:
  evolution_instances:
  evolution_store:
  redis_data: