# Declara que vamos usar a rede externa que já foi criada manualmente
networks:
  radares-net:
    external: true

services:
  # Define o serviço para a aplicação de monitoramento
  microservico-monitoramento:
    container_name: microservico-monitoramento
    # Constrói a imagem a partir do Dockerfile que está nesta mesma pasta
    build:
      context: .
    ports:
      # Expõe a porta da aplicação (ex: 8082) para a sua máquina local
      - "8089:8089"
    environment:
      # Ativa o perfil de produção para usar o application-prod1.properties
      - SPRING_PROFILES_ACTIVE=prod
      # As variáveis para o Telegram serão lidas de um arquivo .env nesta pasta
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      # Conecta este contêiner à nossa rede compartilhada
      - radares-net
    restart: unless-stopped
    depends_on:
      - evolution-api
  # Novo serviço: Evolution API
  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8090:8080" # Acesso externo via http://localhost:8090
    environment:
      - SERVER_URL=http://localhost:8090
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_TOKEN}
      # Desabilita banco de dados complexo para uso local simples (usa arquivo)
      - DATABASE_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - radares-net

volumes:
  evolution_instances:
  evolution_store: