# Declara que vamos usar a rede externa que já foi criada manualmente
networks:
  radares-net:
    external: true

services:
  # Define o serviço para a aplicação de monitoramento
  microservico-monitoramento:
    container_name: microservico-monitoramento
    # Constrói a imagem a partir do Dockerfile que está nesta mesma pasta
    build:
      context: .
    ports:
      # Expõe a porta da aplicação (ex: 8082) para a sua máquina local
      - "8089:8089"
    environment:
      # Ativa o perfil de produção para usar o application-prod1.properties
      - SPRING_PROFILES_ACTIVE=prod
      # Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      # Banco de Dados
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/monitoramento_db
      # RabbitMQ (Usando nomes padrão SPRING_...)
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      # Eureka (Forçando a URL correta aqui para garantir)
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      # Conecta este contêiner à nossa rede compartilhada
      - radares-net
    # Garante que só inicie se os serviços base estiverem saudáveis
    restart: on-failure
